[[redirects]]
  from = "/"
  to = "/tinvay.html"
  status = 200
  force = true

[[redirects]]
  from = "/5-cach-vay-tien-online"
  to = "/bai-viet-1.html"
  status = 200
  force = true

[[redirects]]
  from = "/nhan-tien-vay-online-trong-24h"
  to = "/bai-viet-2.html"
  status = 200
  force = true  

[[redirects]]
  from = "/luu-y-truoc-khi-vay-tien-online"
  to = "/bai-viet-3.html"
  status = 200
  force = true    

[[redirects]]
  from = "/cach-lua-chon-khoan-vay-phu-hop"
  to = "/bai-viet-4.html"
  status = 200
  force = true      