[[redirects]]
  from = "/"
  to = "/tinvay.html"
  status = 200
  force = true

[[redirects]]
  from = "/5-cach-vay-tien-online"
  to = "/bai-viet-1.html"
  status = 200
  force = true

[[redirects]]
  from = "/nhan-tien-vay-online-trong-24h"
  to = "/bai-viet-2.html"
  status = 200
  force = true  

[[redirects]]
  from = "/luu-y-truoc-khi-vay-tien-online"
  to = "/bai-viet-3.html"
  status = 200
  force = true    

[[redirects]]
  from = "/cach-lua-chon-khoan-vay-phu-hop"
  to = "/bai-viet-4.html"
  status = 200
  force = true     

[[redirects]]
  from = "/5-buoc-don-gian-dang-ky-vay-tien-online"
  to = "/bai-viet-5.html"
  status = 200
  force = true        

[[redirects]]
  from = "/xu-ly-no-xau-khi-vay-tien-online"
  to = "/bai-viet-6.html"
  status = 200
  force = true   

[[redirects]]
  from = "/huong-dan-chi-tiet-vay-tien-online-cho-nguoi-moi"
  to = "/tinvay.html"
  status = 200
  force = true        